---
title: "Homework05"
author: "Jay Sullivan"
date: "2025-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Problems
#### Q1
```{r, include=TRUE}
n_dims <- sample(3:10,1,replace = TRUE)
rep(n_dims)
```
```{r, include=TRUE}
n_dims <- sample(3:10,1,replace = TRUE)
# single random integer between 3 and 10
# different function for integer values, whole numbers
# replace true means re sample it the number changes

n_dims2 <- 1:n_dims^2
# create a vector of consecutive integers from 1 to n_dims^2


n_dims3 <- sample(n_dims2)
# use sample function to randomly reshuffle values

m <- matrix(data=n_dims3,nrow= n_dims, ncol = n_dims)
# create a square matrix with these elements

print(m)
# print out the matrix
# Notes: Long list of values

tmatrix <- t(m)
# find a function in r to transpose matrix

print(tmatrix)
# print it out again and note how it has changed
#flips it, so if a number is at position 1,3 it will be moves to 3,1
# if a number is at 3,3 it will stay

x <- sum(tmatrix[1,])
y <- mean(tmatrix[1,])
# Sum and mean of 1st row

x2 <- sum(tmatrix[length(n_dims),])
y2 <- mean(tmatrix[length(n_dims),])
# Sum and mean of last row
# calculate the sum and the mean of the elements in 1st and last row


answer <- eigen(tmatrix)
# eigen() function in matrix


values <- answer$values
answer <- answer$vectors
# $values and $vectors in output



typeof(values)
typeof(answer)
# type is double
# typeof() function to figure out type
```



#### Q2   
```{r, include=TRUE}

my_matrix <- matrix(sample(1:10, 16, replace = TRUE), nrow = 4)
# my_matrix


my_setLogical <- sample(1:20,100, replace = TRUE)
x <- my_setLogical > 10
#my_logical


my_letters <- sample(letters)
#my_letters

newlist <- rbind(my_matrix[2,2],my_setLogical[2],my_letters[2])
#newList

typeof(newlist)
# is a character
#typeof()

y <- c(newlist)
typeof(y)
# it is a character
#combine
```


#### Q3   
####### Create a data frame with the two variables (= columns) and 26 cases (= rows) below:
```{r, include=TRUE}

my_unis <- sample(0:10,26,replace = TRUE)
my_letters <- sample(LETTERS)
rep(my_unis)

datax <- data.frame(my_unis, my_letters)
#Data frame
rep(datax)

datax$my_unis[sample(1:26, 4)] <- NA
#first variable

missing <- which(is.na(datax$my_unis))
#missing row code
print(missing)

datanew <- datax[order(datax$my_letters), ]
#Reorder data frame for second variable in alphabetical order
rep(datanew)

meancolumn <- mean(datax$my_unis, na.rm = TRUE)
# Calc column mean for first variable
rep(meancolumn)


```    


[Return Home](index.html)

